#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: FND-SPA | install_legacy | Setup group
  become_user: root
  become: True
  group:
    name: "{{ spark_group }}"
    system: yes

- name: FND-SPA | install_legacy | Setup user
  become: yes
  user:
    name: "{{ spark_user }}"
    system: yes
    group: "{{ spark_group }}"
    createhome: no
    home: /nonexistent
    shell: /usr/sbin/nologin
    comment: "Apache Spark system user"

- name: FND-SPA | install_legacy | Install OS specific required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: fnd_spark_required_packages

- name: FND-SPA | install_legacy | Update installed packager cache
  become: yes
  install_package:
    cache: update

- name: FND-SPA | install_legacy | Install the spark venv
  become: yes
  install_package:
    name: spark
    service: spark
    state: present

- name: FND-SPA | install_legacy | Uncompress the spark tar
  become: yes
  unarchive:
    copy: no
    creates: >
      "{{ spark_root_dir }}/spark-{{ spark_ver }}-
      bin-hadoop{{ spark_hadoop_ver }}"
    dest: "{{ spark_root_dir }}"
    src: "{{ spark_venv_lib_dir }}/{{ spark_tarball_name }}"

- name: FND-SPA | install_legacy | Untar kafka tarball
  become: yes
  unarchive:
    copy: no
    creates: "{{ spark_venv_lib_dir }}/kafka_2.10-0.8.1.1"
    dest: "{{ spark_venv_lib_dir }}"
    src: "{{ spark_venv_lib_dir }}/kafka_2.10-0.8.1.1.tgz"

- name: FND-SPA | install_legacy | Link lib jars to spark lib directory
  become: yes
  file:
    state: link
    dest: "{{ spark_lib_jars_location }}/{{ item[0] }}"
    src: "{{ spark_venv_lib_dir }}/{{ item[1] }}/{{ item[0] }}"
  with_items:
    - "{{ spark_libs }}"
